### ISSUE TITLE
Very incorrect ranges from lidar

### ISSUE THREAD

**Issue by jisa** [osrf/subt#1001]
CORO_PAM_SENSOR_CONFIG_1, about 2.5 meters above ground (see pictures below), repeatedly, i.e. not just due to noise, reports distance to ground over 10 meters. Up to this moment of complete failure, it has also been overestimating the distance by about 20 % in comparison to estimates based on other sensors. 

```
# rostopic echo /robot/bottom_scan
header:
  seq: 2325
  stamp:
    secs: 46
    nsecs: 540000000
  frame_id: "robot/base_link/bottom_laser"
angle_min: 3.14159274101
angle_max: 3.14159274101
angle_increment: nan
time_increment: 0.0
scan_time: 0.0
range_min: 0.0500000007451
range_max: 40.0
ranges: [10.705933570861816]
intensities: [0.0]
---
header: 
  seq: 2326
  stamp: 
    secs: 46
    nsecs: 560000000
  frame_id: "robot/base_link/bottom_laser"
angle_min: 3.14159274101
angle_max: 3.14159274101
angle_increment: nan
time_increment: 0.0
scan_time: 0.0
range_min: 0.0500000007451
range_max: 40.0
ranges: [10.632636070251465]
intensities: [0.0]
---
header: 
  seq: 2327
  stamp: 
    secs: 46
    nsecs: 580000000
  frame_id: "robot/base_link/bottom_laser"
angle_min: 3.14159274101
angle_max: 3.14159274101
angle_increment: nan
time_increment: 0.0
scan_time: 0.0
range_min: 0.0500000007451
range_max: 40.0
ranges: [10.578147888183594]
intensities: [0.0]
---
header: 
  seq: 2328
  stamp: 
    secs: 46
    nsecs: 600000000
  frame_id: "robot/base_link/bottom_laser"
angle_min: 3.14159274101
angle_max: 3.14159274101
angle_increment: nan
time_increment: 0.0
scan_time: 0.0
range_min: 0.0500000007451
range_max: 40.0
ranges: [10.461398124694824]
intensities: [0.0]
```
![drone-lidar](https://user-images.githubusercontent.com/686527/130300151-97fc2784-f56e-435a-b416-e58a420c5649.jpg)
![drone-lidar2](https://user-images.githubusercontent.com/686527/130300288-725eab50-58c6-4054-8aa8-1d8825cc5963.jpg)

**Comment by jisa** [comment]
After that, when it gets over the shaft, it underestimates distance to the bottom.

```
# rostopic echo /robot/bottom_scan
header: 
  seq: 2596
  stamp: 
    secs: 51
    nsecs: 960000000
  frame_id: "robot/base_link/bottom_laser"
angle_min: 3.14159274101
angle_max: 3.14159274101
angle_increment: nan
time_increment: 0.0
scan_time: 0.0
range_min: 0.0500000007451
range_max: 40.0
ranges: [5.705638408660889]
intensities: [0.0]
---
```

At that point, the drone is sufficiently horizontal not to be pointing the lidar to a wall:
```
# rostopic echo /robot/imu/data
header:
  seq: 12747
  stamp:
    secs: 51
    nsecs: 948000000
  frame_id: "robot/base_link/imu_sensor"
orientation:
  x: -0.0141953380262
  y: -0.0169637710734
  z: 0.600932680144
  w: 0.798993514858
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity:
  x: 0.00325
  y: 0.0285
  z: 0.87225
angular_velocity_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
linear_acceleration:
  x: 0.015
  y: 0.06
  z: 9.675
linear_acceleration_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---
```

![drone-lidar3](https://user-images.githubusercontent.com/686527/130313087-685d2d9a-5cf8-4cb5-8e6e-7a3f85da4d51.jpg)
![drone-lidar4](https://user-images.githubusercontent.com/686527/130313091-9c7febbc-c578-4ccb-9192-97283b833d4c.jpg)
![drone-lidar5](https://user-images.githubusercontent.com/686527/130313093-eed35cdd-e718-4365-a334-bec1a09185d4.jpg)
