### ISSUE TITLE
Local Cloudsim hangs up on comms broker

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#316]
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/316)) by Paul Jurczak (Bitbucket: [pauljurczak](https://bitbucket.org/%7Bd17ee528-259a-4ff4-b5b0-007442ea3edb%7D/)).**

----------------------------------------
I’m following the tutorial with a solution built and tested in catkin workspace. I created Docker image with this recipe:

```
FROM osrf/subt-virtual-testbed:subt_solution_latest

COPY docker ~/subt_ws/install/share
CMD ~/subt_ws/install/share/run_sim.bash
```

`run_sim.bash`:

```
. /opt/ros/melodic/setup.bash
. ~/subt_ws/install/setup.sh

roslaunch st.launch
```

`st.launch`:

```
<launch>
  <node pkg="robot_localization" type="ekf_localization_node" name="robot_localization_ekf_node_odom" clear_params="true">
    <rosparam command="load" file="$(dirname)/ekf_localization.yaml" />
  </node>
  <node pkg="st" type="st_node" name="st_node" clear_params="true"> </node>
</launch> 
```

`docker_compose.yaml`:

```
version: "2.4"
services:

  # The sim container runs Gazebo and all simulation plugins.
  # In this example, two robots are started with the names X1 and X2.
  sim:
    image: osrf/subt-virtual-testbed:cloudsim_sim_latest
    command: cloudsim_sim.ign headless:=true worldName:=urban_qual robotName1:=X1 robotConfig1:=COSTAR_HUSKY_SENSOR_CONFIG_1
    networks:
      sim_net:
        ipv4_address: 172.28.1.1
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - IGN_PARTITION=sim
      - IGN_IP=172.28.1.1
    env_file: .env  
    privileged: true
    runtime: nvidia
    security_opt:
      - seccomp=unconfined
    volumes:
      - "/tmp/.docker.xauth:/tmp/.docker.xauth"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/etc/localtime:/etc/localtime:ro"
      - "/dev/input:/dev/input" 

  # The bridge container relays a sub-set of information from the sim container
  # to the solution container. This bridge container will relay information
  # for the X1 robot
  bridge1:
    image: osrf/subt-virtual-testbed:cloudsim_bridge_latest
    # Relay topics and service for X1
    command: worldName:=urban_qual robotName1:=X1 robotConfig1:=COSTAR_HUSKY_SENSOR_CONFIG_1
    # The bridge needs two networks. One for simulation and one for the
    # solution.
    networks:
      relay_net1:
        ipv4_address: 172.29.1.1
      sim_net:
        ipv4_address: 172.28.1.2
    environment:
      - IGN_PARTITION=sim
      - IGN_IP=172.28.1.2
      - ROS_MASTER_URI=http://172.29.1.1:11311
    env_file: .env
    depends_on:
      - "sim"

  # The solution container runs control code for a single robot. This
  # solution container connects to the first bridge, and therefore controls
  # the X1 robot.
  solution1:
    image: st:latest
    networks:
      relay_net1:
        ipv4_address: 172.29.1.2
    environment:
      - ROS_MASTER_URI=http://172.29.1.1:11311
    runtime: nvidia
    depends_on:
      - "bridge1"

  
# Definition of the networks.
networks:
  sim_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  relay_net1:
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
```

I tried it on two different PCs and on one it hangs up here:

```
sim_1        | [Msg] Publishing pose messages on [/world/urban_qual/pose/info]
sim_1        | [Msg] Publishing dynamic pose messages on [/world/urban_qual/dynamic_pose/info]
sim_1        | [Dbg] [CommsBrokerPlugin.cc:210] Using [visibility_range] comms model
sim_1        | [Msg] Starting SubT comms broker
```

on the other one `Robot [X1] is too far from the staging area`\` at spawn:

```
sim_1        | [Msg] Loaded level [70]
sim_1        | [Msg] Loaded level [71]
sim_1        | [Msg] Loaded level [74]
sim_1        | [Msg] Loaded level [75]
sim_1        | [Msg] Publishing laser scans on [world/urban_qual/model/X1/link/base_link/sensor/front_cliff_laser/scan]
sim_1        | [Msg] Publishing laser scans on [world/urban_qual/model/X1/link/base_link/sensor/front_laser/scan]
sim_1        | [Msg] Unloaded level [12]
sim_1        | [Msg] Unloaded level [70]
sim_1        | [Msg] Unloaded level [16]
sim_1        | [Msg] Unloaded level [8]
sim_1        | [Msg] Unloaded level [71]
sim_1        | [Msg] Unloaded level [36]
sim_1        | [Msg] Unloaded level [4]
sim_1        | [Msg] Unloaded level [5]
sim_1        | [Msg] Unloaded level [6]
sim_1        | [Msg] Unloaded level [7]
sim_1        | [Msg] Unloaded level [9]
sim_1        | [Msg] Unloaded level [10]
sim_1        | [Msg] Unloaded level [11]
sim_1        | [Msg] Unloaded level [13]
sim_1        | [Msg] Unloaded level [14]
sim_1        | [Msg] Unloaded level [15]
sim_1        | [Msg] Unloaded level [18]
sim_1        | [Msg] Unloaded level [19]
sim_1        | [Msg] Unloaded level [20]
sim_1        | [Msg] Unloaded level [21]
sim_1        | [Msg] Unloaded level [22]
sim_1        | [Msg] Unloaded level [23]
sim_1        | [Msg] Unloaded level [24]
sim_1        | [Msg] Unloaded level [25]
sim_1        | [Msg] Unloaded level [34]
sim_1        | [Msg] Unloaded level [35]
sim_1        | [Msg] Unloaded level [39]
sim_1        | [Msg] Unloaded level [40[[Err] [GameLogicPlugin.cc:1035] [GameLogicPlugin]: Robot [X1] is too far from the staging area. Ignoring PoseFromArtifact request
solution1_1  | [ERROR] [1578054993.553735358, 6.044000000]: Failed to call pose_from_artifact_origin service, robot may not exist, be outside staging area, or the service is not available.
sim_1        | 0m]
sim_1        | [Msg] Unloaded level [48]
sim_1        | [Msg] Unloaded level [49]
```

‌
