### ISSUE TITLE
drone rotors never start turing

### ISSUE THREAD

**Issue by zwn** [osrf/subt#669]
In simulation `eaee7507-5006-4529-a2c0-1f283c9481b0` the drone named A600L never took off.

When analyzing the problem, I was able to confirm that some speed commands got all the way to the process `/A600L/ros_ign_bridge_twist` - see this excerpt from `rostopic_stats_logger.log`:

```yml
topic: "/A600L/cmd_vel"
node_pub: "/A600L_proxy"
node_sub: "/A600L/ros_ign_bridge_twist"
window_start: 
  secs: 86
  nsecs:         0
window_stop: 
  secs: 89
  nsecs:         0
delivered_msgs: 3
dropped_msgs: 0
```

Further analysis of the file `state.tlog` revealed that the drone rotors never started to turn. In the file in the "pose" message there are two poses with the name `rotor_0` and different ids - 175 and 224. The rotor with id 224 starts to move at around 92s which directly corresponds to our commands to the other drone in the simulation. The rotor with id 175 never turns (its orientation never significantly changes except some noise).
