### ISSUE TITLE
Comms not present in a simulation

### ISSUE THREAD

**Issue by malcolmst** [osrf/subt#673]
I just had an issue when running a cave simple 1 scenario (running on a local system) that comms was not present between any of the robots. No messages were received, and calling the neighbors function, no neighbors aside from the robot itself appeared. I didn't see any obvious errors in the logs, but I did notice one thing in `events.yml`: it seems one of the robots dropped a breadcrumb before leaving the staging area. 

```
- event:
  id: 5
  type: breadcrumb_deploy
  time_sec: 117
  robot: X2N2
- event:
  id: 6
  type: detect
  time_sec: 120
  detector: staging_area
  robot: X2N2
  state: exit
```

Could this be the cause? I have limited time for debugging at the moment (probably will just revert some of my recent breadcrumb-related changes), but I'd be happy to provide any additional logs.
