### ISSUE TITLE
Cloudsim: Backpack in staging area

### ISSUE THREAD

**Issue by peci1** [osrf/subt#750]
In simulation e097b600-5ff5-4ce0-a687-8079f46d0815, there was a backpack in staging area. It was world Cave Circuit 07. Another run in the same world does not show the backpack. But in the mentioned run, it was really there, as it generated events between time 23 and 51, which would be impossible with the backpack in correct position.

![image](https://user-images.githubusercontent.com/182533/104385464-91a2f100-5533-11eb-8a66-753039d60533.png)

The generated events:

```YAML
- event:
  id: 6
  type: detect
  time_sec: 23
  detector: backpack_1
  robot: X1
  state: enter
  extra:
    type: artifact_proximity
- event:
  id: 7
  type: detect
  time_sec: 23
  detector: backpack_1
  robot: X2
  state: enter
  extra:
    type: artifact_proximity
- event:
  id: 8
  type: detect
  time_sec: 23
  detector: backpack_1
  robot: X3
  state: enter
  extra:
    type: artifact_proximity
- event:
  id: 9
  type: detect
  time_sec: 23
  detector: backpack_1
  robot: uav2
  state: enter
  extra:
    type: artifact_proximity
- event:
  id: 10
  type: detect
  time_sec: 23
  detector: backpack_1
  robot: uav4
  state: enter
  extra:
    type: artifact_proximity
- event:
  id: 11
  type: detect
  time_sec: 23
  detector: backpack_1
  robot: uav5
  state: enter
  extra:
    type: artifact_proximity
- event:
  id: 12
  type: detect
  time_sec: 44
  detector: backpack_1
  robot: X3
  state: exit
  extra:
    type: artifact_proximity
- event:
  id: 13
  type: detect
  time_sec: 46
  detector: backpack_1
  robot: X2
  state: exit
  extra:
    type: artifact_proximity
- event:
  id: 14
  type: detect
  time_sec: 51
  detector: backpack_1
  robot: X1
  state: exit
  extra:
    type: artifact_proximity
```
