### ISSUE TITLE
X500 UAV not treated as a robot

### ISSUE THREAD

**Issue by peci1** [osrf/subt#887]
On fuel database, X500 is not in section Robots. On live cloudsim view, X500 is in section Other. In cloudsim run.yml, X500 is not in the list of robots:

```
robots:
  X1:
    platform: X1
    config: EXPLORER_X1_SENSOR_CONFIG_2
marsupials:
  {}
robot_count: 4
```
