### ISSUE TITLE
events.yml events for helmet reports missing closest artifact

### ISSUE THREAD

**Issue by fcseidl** [osrf/subt#959]
The ```events.yml``` file contained in the logs for a cloud run is supposed to show when a robot reports an artifact. For example, here is the record of a successful report in a recent cloud run:

```
- event:
  id: 192
  type: artifact_report_attempt
  time_sec: 2181
  reported_pose_world_frame: -8.61153 -160.719 -8.96568
  reported_pose_artifact_frame: 1.88847 -160.719 -8.96568
  reported_artifact_type: TYPE_RESCUE_RANDY
  closest_artifact_name: rescue_randy_1
  distance: 2.7189
  points_scored: 1
  total_score: 3
```

That's how the reports should be recorded in ```events.yml```. But in the same run, I encountered this event, which does not list a closet artifact, and has a negative distance. This happens again for another helmet report in the same run.

```
- event:
  id: 209
  type: artifact_report_attempt
  time_sec: 3504
  reported_pose_world_frame: 10.4518 7.86749 8.89695
  reported_pose_artifact_frame: 20.9518 7.86749 8.89695
  reported_artifact_type: TYPE_HELMET
  closest_artifact_name:
  distance: -1
  points_scored: 0
  total_score: 3
```

There should always be _some_ closest artifact, even for incorrect reports, even when the closest artifact is not of the type reported. Because I've seen it for multiple helmet reports, my guess is that something specific is wrong with the way reports of helmet artifacts get handled.
