### ISSUE TITLE
Collision detector is way too sensitive

### ISSUE THREAD

**Issue by fcseidl** [osrf/subt#967]
Robots frequently incur [collision damage](https://github.com/osrf/subt/pull/916) from minor jolts that definitely should not cause any serious damage. For instance, below is a recording of a UGV disabling itself by driving over an urban hallway threshold. The robot has been manually ordered to maintain its speed, but after it hits the thin metal strip it is too damaged to continue, demonstrating unrealistically extreme fragility. (Not to mention that even if every servo in the robot _did_ break instantly on impact, one would still expect the back wheels to clear the metal before the robot's momentum was spent.)

The github discussion linked above seems to provide the only explanation of how collision detection actually works. It suggests that every mechanical part on a robot will be completely disabled whenever the robot experiences an impulse greater than what would be produced by a 7.7 cm fall. This threshold is far too low, as any real robot would almost certainly withstand such a short fall. The result is that UGVs and UAVs alike can lose their actuators silently as a result of the tiniest impacts.

https://user-images.githubusercontent.com/53065461/124317114-a7898a00-db44-11eb-9a85-fcdec2788a01.mov

**Comment by snkitche** [comment]
@nkoenig 
@angelacmaio 

Code freeze for the final event is tomorrow. We will continue to test this locally to make sure we understand the parameters and effects, but we would at least like to know if this is expected behavior. 

We are also seeing dozens of collision events in the logs with wildly varying ke, despite the most frequent types of observed behavior being similar to this. 

Please let us know if there is additional info we can provide.

**Comment by angelacmaio** [comment]
Which robots have you experienced this issue with, and what are the KE difference values reported during the collision event?

**Comment by fcseidl** [comment]
We've observed strange collisions with the coro allies (featured in the video above) and the ctu cras norlab x500s. The x500s are particularly bad. The event log seemingly reports the robot KE and KE threshold, but no KE difference. Below is an excerpt from one of our logfiles. The robot in question is a ctu cras norlab x500. Note that several collision events seem to occur in extremely rapid succession.

```
- event:
  id: 151
  type: collision
  ke: 6.42471
  ke_threshold: 2.54927
  link: base_link
  time_sec: 1160
  robot: Xd
- event:
  id: 152
  type: collision
  ke: 29.0043
  ke_threshold: 2.54927
  link: base_link
  time_sec: 1160
  robot: Xd
- event:
  id: 153
  type: collision
  ke: 4.98783
  ke_threshold: 2.54927
  link: base_link
  time_sec: 1160
  robot: Xd
- event:
  id: 154
  type: collision
  ke: 2.97861
  ke_threshold: 2.54927
  link: base_link
  time_sec: 1161
  robot: Xd
```

**Comment by snkitche** [comment]
The ke can get much larger than that too: 
```
- event:
  id: 304
  type: collision
  ke: 315.947
  ke_threshold: 2.54927
  link: base_link
  time_sec: 1370
  robot: Xf
- event:
  id: 305
  type: collision
  ke: 117.277
  ke_threshold: 2.54927
  link: base_link
  time_sec: 1370
  robot: Xf
```
```
- event:
  id: 222
  type: collision
  ke: 3479.91
  ke_threshold: 2.54927
  link: base_link
  time_sec: 961
  robot: Xd
- event:
  id: 223
  type: collision
  ke: 9398.13
  ke_threshold: 2.54927
  link: base_link
  time_sec: 961
  robot: Xd
```
```
- event:
  id: 93
  type: collision
  ke: 240.812
  ke_threshold: 36.0002
  link: base_link
  time_sec: 233
  robot: Xa
- event:
  id: 94
  type: collision
  ke: 667.962
  ke_threshold: 36.0002
  link: base_link
  time_sec: 233
  robot: Xa
- event:
  id: 95
  type: collision
  ke: 96.6824
  ke_threshold: 36.0002
  link: base_link
  time_sec: 233
  robot: Xa
- event:
  id: 96
  type: collision
  ke: 625.672
  ke_threshold: 36.0002
  link: base_link
  time_sec: 234
  robot: Xa
- event:
  id: 97
  type: collision
  ke: 120.842
  ke_threshold: 36.0002
  link: base_link
  time_sec: 234
  robot: Xa
```
